### ISSUE TITLE
Getting flate onto a WebWorker

### ISSUE THREAD

**Issue by TreeOfSelf** [drbh/wasm-flate#2]
I am trying to figure out how to get this to run in a browser webworker. I have tried downloading the .wasm through through WAPM, but when I try to use the exports.zlib_encode it always returns undefined. 

When I run it through the bootstrap.js it works great, but then it is stuck on the main thread.
Is there anyway I can get this running on a WebWorker?

**Comment by drbh** [comment]
Hey @TreeOfSelf 

Thanks for the feedback - I have not Q/A'd the library from WAPM, it should work from NPM no issue - or pull the repo down and build it locally. 

Moving the processing to a web worker is a great idea. 

I have not done the research on what the next best steps are for implementing this on webworkers - maybe you can help?

### Resources
https://rustwasm.github.io/2018/10/24/multithreading-rust-and-wasm.html
https://github.com/rustwasm/rust-webpack-template/issues/44
https://github.com/cars10/rust-wasm-webworker-example
https://asquera.de/blog/2018-10-01/webassembly-and-wasm-bindgen/


Do you have any insights? 😀

**Comment by drbh** [comment]
I saw a similar (maybe your post) on reddit and have a working solution for adding in the JS shim after loading in the binary.

Checkout the gist: https://gist.github.com/drbh/2d4724a042ded7f40c36d028f6ce7140

I hope this suffices for your use-case. Please let me know

**Comment by TreeOfSelf** [comment]
I am indeed the one to post to Reddit, but, functionality out of the box like this I think will help a lot of people. The issue with the functions not returning anything was completely on my end. This is actually the first WebAssembly project I have ever worked with ever, so I didn't know that the javascript functions needed the bootstrap (or the awesome file you just provided) to be able to correctly send their function inputs. 

This is perfect, and I do think this will help a lot of other people. In the limited testing I have done, the compression to speed ratio is the best with wasm-flate. I am using it for a hobby game project involving voxels to compress block data in a chunk for map saving / loading and wanted to compress chunks in the background as the game plays instead of compressing them all at once during saving. 

Thank you so much for your quick response and care. I appreciate your amazing work .
