### ISSUE TITLE
Using wasm-flate with webpack

### ISSUE THREAD

**Issue by GeorchW** [drbh/wasm-flate#3]
At the moment, a simple `require('wasm-flate')` does not work in a webpack environment, due to the dependency on `fs` that is used to load the wasm code.

Btw: Is it possible to shrink the code a little more, such that the asynchronous loading is less neccessary? Right now, the fact that pako is only 45 KB minified is quite an argument.

**Comment by drbh** [comment]
@GeorchW thanks for the feedback, I haven't thought about the library size and will look into reducing the `.wasm` and `.js` shims. 

As to the dependencies, `wasm-flate` doesn't have any dependencies and can be run with native JS. `fs` in this case may be used to import the wasm binary before wrapping JS shims around those functions. Those shims are the interface that lets you make calls from JS. You can load the wasm files in other ways - like fetching it from the browser.
 _note - I am going to look in to the possibility of inlining the wasm file in the JS - that would be cool._

**looking at file size**

The wasm library is ~170 KB which following some of the example here (https://rustwasm.github.io/book/game-of-life/code-size.html) - I might be able to reduce.

The JS shim files are < 500 Bytes, so i'll ignore those for now.

**about asynchronous loading**

As to the asynchronous loading - that is suggested (I thought enforced until now) by the WebAssembly spec. Here's a link and quote from their docs

> The WebAssembly.Module() constructor function can be called to synchronously compile given WebAssembly binary code. However, the primary way to get a Module is through an asynchronous compilation function like WebAssembly.compile().
[docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Module)

I plan on making some updates soon, for better wasm to JS shims, and try to reduce the wasm binary size as suggested in those docs.

Until those updates, check out this cdn dependent [gist](https://gist.github.com/drbh/c003daa776344f715d81ec3de170b3fa) as an alternative way to load in the wasm file. 

Hope this is helpful! Let me know if there are other changes or difficultly with the library!

**Comment by drbh** [comment]
bump: I looked into inlining the wasm as a base 64 string - and it works! check out this gist for an example embedding in node [gist](https://gist.github.com/drbh/24496aaa863b8faa549cd05cd939f587)

_Note: this is still > 170 KB because it is the currently available wasm-flate binary as a b64 string_

**Comment by GeorchW** [comment]
Thanks for the quick update! I will look into your last gist, that one looks very promising.

**Comment by jimmykane** [comment]
Hi could someone help me on loading this lib with Webpack? I would like to use it in an Angular app
