### ISSUE TITLE
I updated from beta 0.1.0 and got errors  on 1.0.2

### ISSUE THREAD

**Issue by jimmykane** [drbh/wasm-flate#9]
I updated from beta 0.1.0 and got errors  on 1.0.2 

We had discussed about the issue with webpack and beta 0.1.0 fixed it. 

I am cofused now as it updated to 1.0.2 and the issue is back.

**Comment by drbh** [comment]
Apologizes for the inconvenience try the newer version build for a bundler https://www.npmjs.com/package/wasm-flate/v/1.0.2-bundler

**Comment by jimmykane** [comment]
Thanks fixed
